taskkill -f -im qbittorrent.exe
taskkill -f -im Dropbox.exe
taskkill -f -im MEGAsync.exe
taskkill -f -im googledrivesync.exe
taskkill -f -im GoogleDriveFS.exe
taskkill -f -im qbittorrent.exe
taskkill -f -im anydesk.exe
taskkill -f -im OneDrive.exe
taskkill -f -im discord.exe
taskkill -f -im steam.exe
